name: Update the code

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  MODEL_VERSION: "v2"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Snapd
        run: |
          sudo apt-get install -y snapd
      - name: Install yq using Snap
        run: |
          sudo snap install yq
      - name: "Update Data"
        shell: bash
        run: |    
          export DOCKER_IMAGE="test-image:latest"
          export TAG=latest
          yq eval '.[0].value = env(DOCKER_IMAGE)' test.yaml
          yq eval '.[1].value = env(TAG)' test.yaml
          yq eval '.[2].value = env(MODEL_VERSION)' test.yaml
      - name: Commit files
        run: |
          cat test.yaml