name: TAG_CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Display tag information
      run: |
        echo "Push event with tag: ${{ github.ref_name }}"
        echo "Tag name: ${{ github.event.ref_name }}"
